### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by kostis** [adamkapetis/compilers#2]
First issue to fix is to clean up you repository.

It seems that it also contains generated files (e.g. `.o` ones under the `llvm` dir, `.imm` files under `grace_programs`, the `llvm/gracec` executable, etc.). 

Most of these files are not platform/OS independent and therefore should not be in the repository.

More generally, there is usually very little reason for a repo to contain files that can be generated.

**Comment by gmarkantonatos** [comment]
# Clean up repo
We cleaned up our repo directories. Non-essential files were deleted.
